version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: 'docker/server/Dockerfile'
      args:
        BUILD_DEV: ${BUILD_DEV:-true}
    environment:
      DATABASE_URL: &db 'postgresql://postgres:postgres@postgres:5432/postgres'
      SECRET_KEY: &secret_key ${SECRET_KEY:-secret_key}

      SENTRY_DSN: ${SENTRY_DSN:-}
      SENTRY_RELEASE: ${SENTRY_RELEASE:-unreleased}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT:-dev}

      LOGGING_LEVEL: 'DEBUG'
      PYTHONASYNCIODEBUG: 'true'
      PYTEST_ADDOPTS: ${PYTEST_ADDOPTS:-}
    ports:
      - '${PORT:-8000}:8000'
    volumes:
      - '.:/app/'
    restart: always
    init: true
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  migrations:
    build:
      context: .
      dockerfile: 'docker/server/Dockerfile'
      args:
        BUILD_DEV: ${BUILD_DEV:-dev}
    command: alembic upgrade head
    environment:
      DATABASE_URL: *db
      SECRET_KEY: *secret_key
    volumes:
      - '.:/app/'
    depends_on:
      - postgres

  postgres:
    image: 'postgres:11.2'
    environment:
      POSTGRES_PASSWORD: 'postgres'

  # locust_master:
  #   build:
  #     context: .
  #     dockerfile: 'docker/locust/Dockerfile'
  #   command: --host http://server:8000/api
  #   ports:
  #     - '8089:8089'
  #   volumes:
  #     - './docker/locust/locustfile.py:/locustfile.py'
  #   depends_on:
  #     - server
